In [1]:
import numpy as np

## Creating numpy/n-D arrays


In [6]:
# 1D array
arr1=np.array([1,2,3,4,5])
arr1


array([1, 2, 3, 4, 5])

In [8]:
print (arr1)
type(arr1)

[1 2 3 4 5]


numpy.ndarray

In [11]:
# 2D array
arr2=np.array([[23,45,64,75],[23,53,64,64]])
arr2

array([[23, 45, 64, 75],
       [23, 53, 64, 64]])

In [12]:
print(arr2)

[[23 45 64 75]
 [23 53 64 64]]


In [20]:
arr3=np.ones([2,3])
arr3

array([[1., 1., 1.],
       [1., 1., 1.]])

In [22]:
arr4=np.zeros([3,3])
arr4

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [24]:
arr5=np.identity(5)
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
arr6=np.arange(6,21) # arrange create array while range create list
arr6

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [35]:
arr6=np.arange(5,16,2) # 2 gap
arr6

array([ 5,  7,  9, 11, 13, 15])

In [38]:
arr7=np.linspace(4,21,10) # lower range, upper range and equdistance jump
arr7

array([ 4.        ,  5.88888889,  7.77777778,  9.66666667, 11.55555556,
       13.44444444, 15.33333333, 17.22222222, 19.11111111, 21.        ])

In [40]:
arr8=arr7.copy() # the same as we have copied it
arr8

array([ 4.        ,  5.88888889,  7.77777778,  9.66666667, 11.55555556,
       13.44444444, 15.33333333, 17.22222222, 19.11111111, 21.        ])

In [42]:
arr1.shape

(5,)

In [58]:
arr2

array([[23, 45, 64, 75],
       [23, 53, 64, 64]])

In [57]:
arr2.shape # 2 rows 4 columns

(2, 4)

In [2]:
arr9=np.array([[[1,2],[2,3]],[[4,6],[4,6]]])
arr9

array([[[1, 2],
        [2, 3]],

       [[4, 6],
        [4, 6]]])

In [3]:
arr9.shape # attribute 2 rows, 2 columns, 2 matrices

(2, 2, 2)

In [50]:
arr9.ndim # dimension

3

## Attributes vs Function
***Attributes are not function they have access to both funtion and data***

In [60]:
arr9.size

8

In [69]:
arr9.itemsize # in bytes single item size


8

In [72]:
arr9.dtype # data type

dtype('int64')

In [81]:
arr9.astype("bool") # convert to that datatype

array([[[ True,  True],
        [ True,  True]],

       [[ True,  True],
        [ True,  True]]])

arr9.itemsize

## Numpy Array VS Python List
- less Memory
- faster
-  convenient

In [83]:
lista=range(100)
arr11=np.arange(100)
lista


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [84]:
arr11

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [85]:
# now check the memory size
import sys


In [87]:
print(sys.getsizeof(87)*len(lista))

2800


In [89]:
print(arr11.itemsize*arr11.size)

800


In [6]:
# now check the faster 
import time #to measure speed

In [13]:
# normal python code without library
x=range(10000000)
y=range(10000000, 20000000)
start_time=time.time() # time function give the current time
c=[(x+y) for x,y in zip(x,y)] # t|ake each element of every list and combine it and then add it to a new list
print(time.time()-start_time) # sub the start time that is before starting the function

1.4799833297729492


In [14]:
# now we do for numpy
a=np.arange(10000000)
b=np.arange(10000000, 20000000)
start_time=time.time()
c=a+b
print(time.time()-start_time)

0.2053356170654297


 # Indexing, Slicing and Iteration

In [7]:
arr12=np.arange(24).reshape(6,4)
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [20]:
arr12[2:5]
arr12[5:6,1:3]
arr12[:,1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18],
       [21, 22]])

In [13]:
arr12[:,2] # column 3rd 


array([ 2,  6, 10, 14, 18, 22])

In [16]:
arr12[4:6,1:3] # 5th and 6th column, 2nd and 3rd column

array([[17, 18],
       [21, 22]])

In [21]:
for i in arr12:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [23]:
for i in np.nditer(arr12):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
